# headers_config.py
GetUserInfo_Header = {
    'Accept':	'application/json, text/plain, */*',
    'Accept-Encoding':	'gzip, deflate, br',
    'Accept-Language':	'zh-CN,zh;q=0.9',
    'Connection':	'keep-alive',
    'Content-Length':	2,
    'Content-Type':	'application/json',
    'Host':	'angelapi.bluemoon.com.cn',
    'Origin':	'https://angelapi.bluemoon.com.cn',
    'Referer':	'https://angelapi.bluemoon.com.cn/portal-admin/admin/index.html',
    'sec-ch-ua':	'"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform':	'"Windows"',
    'Sec-Fetch-Dest':	'empty',
    'Sec-Fetch-Mode':	'cors',
    'Sec-Fetch-Site':	'same-origin',
    'User-Agent':	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
    'X-Requested-With':	'XMLHttpRequest',
    'Cookie':	'JSESSIONID=095CBA23595D240A14677C60C9F5E10D; customerId=80512165;',
    }